// +build !ignore_autogenerated

/**
 * Copyright 2018 Rafael Fernández López <ereslibre@ereslibre.es>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 **/

// Code generated by conversion-gen. DO NOT EDIT.

package v1alpha1

import (
	unsafe "unsafe"

	cluster "github.com/ereslibre/cluster-apiserver/pkg/apis/cluster"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*User)(nil), (*cluster.User)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_User_To_cluster_User(a.(*User), b.(*cluster.User), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*cluster.User)(nil), (*User)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_cluster_User_To_v1alpha1_User(a.(*cluster.User), b.(*User), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*UserList)(nil), (*cluster.UserList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_UserList_To_cluster_UserList(a.(*UserList), b.(*cluster.UserList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*cluster.UserList)(nil), (*UserList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_cluster_UserList_To_v1alpha1_UserList(a.(*cluster.UserList), b.(*UserList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*UserSpec)(nil), (*cluster.UserSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_UserSpec_To_cluster_UserSpec(a.(*UserSpec), b.(*cluster.UserSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*cluster.UserSpec)(nil), (*UserSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_cluster_UserSpec_To_v1alpha1_UserSpec(a.(*cluster.UserSpec), b.(*UserSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*UserStatus)(nil), (*cluster.UserStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_UserStatus_To_cluster_UserStatus(a.(*UserStatus), b.(*cluster.UserStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*cluster.UserStatus)(nil), (*UserStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_cluster_UserStatus_To_v1alpha1_UserStatus(a.(*cluster.UserStatus), b.(*UserStatus), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1alpha1_User_To_cluster_User(in *User, out *cluster.User, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_UserSpec_To_cluster_UserSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_UserStatus_To_cluster_UserStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_User_To_cluster_User is an autogenerated conversion function.
func Convert_v1alpha1_User_To_cluster_User(in *User, out *cluster.User, s conversion.Scope) error {
	return autoConvert_v1alpha1_User_To_cluster_User(in, out, s)
}

func autoConvert_cluster_User_To_v1alpha1_User(in *cluster.User, out *User, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_cluster_UserSpec_To_v1alpha1_UserSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_cluster_UserStatus_To_v1alpha1_UserStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_cluster_User_To_v1alpha1_User is an autogenerated conversion function.
func Convert_cluster_User_To_v1alpha1_User(in *cluster.User, out *User, s conversion.Scope) error {
	return autoConvert_cluster_User_To_v1alpha1_User(in, out, s)
}

func autoConvert_v1alpha1_UserList_To_cluster_UserList(in *UserList, out *cluster.UserList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]cluster.User)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha1_UserList_To_cluster_UserList is an autogenerated conversion function.
func Convert_v1alpha1_UserList_To_cluster_UserList(in *UserList, out *cluster.UserList, s conversion.Scope) error {
	return autoConvert_v1alpha1_UserList_To_cluster_UserList(in, out, s)
}

func autoConvert_cluster_UserList_To_v1alpha1_UserList(in *cluster.UserList, out *UserList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]User)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_cluster_UserList_To_v1alpha1_UserList is an autogenerated conversion function.
func Convert_cluster_UserList_To_v1alpha1_UserList(in *cluster.UserList, out *UserList, s conversion.Scope) error {
	return autoConvert_cluster_UserList_To_v1alpha1_UserList(in, out, s)
}

func autoConvert_v1alpha1_UserSpec_To_cluster_UserSpec(in *UserSpec, out *cluster.UserSpec, s conversion.Scope) error {
	out.Username = in.Username
	out.Password = in.Password
	out.Role = in.Role
	return nil
}

// Convert_v1alpha1_UserSpec_To_cluster_UserSpec is an autogenerated conversion function.
func Convert_v1alpha1_UserSpec_To_cluster_UserSpec(in *UserSpec, out *cluster.UserSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_UserSpec_To_cluster_UserSpec(in, out, s)
}

func autoConvert_cluster_UserSpec_To_v1alpha1_UserSpec(in *cluster.UserSpec, out *UserSpec, s conversion.Scope) error {
	out.Username = in.Username
	out.Password = in.Password
	out.Role = in.Role
	return nil
}

// Convert_cluster_UserSpec_To_v1alpha1_UserSpec is an autogenerated conversion function.
func Convert_cluster_UserSpec_To_v1alpha1_UserSpec(in *cluster.UserSpec, out *UserSpec, s conversion.Scope) error {
	return autoConvert_cluster_UserSpec_To_v1alpha1_UserSpec(in, out, s)
}

func autoConvert_v1alpha1_UserStatus_To_cluster_UserStatus(in *UserStatus, out *cluster.UserStatus, s conversion.Scope) error {
	return nil
}

// Convert_v1alpha1_UserStatus_To_cluster_UserStatus is an autogenerated conversion function.
func Convert_v1alpha1_UserStatus_To_cluster_UserStatus(in *UserStatus, out *cluster.UserStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_UserStatus_To_cluster_UserStatus(in, out, s)
}

func autoConvert_cluster_UserStatus_To_v1alpha1_UserStatus(in *cluster.UserStatus, out *UserStatus, s conversion.Scope) error {
	return nil
}

// Convert_cluster_UserStatus_To_v1alpha1_UserStatus is an autogenerated conversion function.
func Convert_cluster_UserStatus_To_v1alpha1_UserStatus(in *cluster.UserStatus, out *UserStatus, s conversion.Scope) error {
	return autoConvert_cluster_UserStatus_To_v1alpha1_UserStatus(in, out, s)
}
