apiVersion: v1
kind: Namespace
metadata:
  name: cluster
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: apiserver
  namespace: cluster
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-apiserver-clusterrolebinding
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: ""
subjects:
- kind: ServiceAccount
  name: apiserver
  namespace: cluster
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cluster-apiserver
  namespace: cluster
  labels:
    app: apiserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apiserver
  template:
    metadata:
      labels:
        app: apiserver
    spec:
      serviceAccountName: apiserver
      containers:
      - name: cluster-apiserver
        image: cluster-apiserver:latest
        imagePullPolicy: Never
        command: [ "/cluster-apiserver", "--etcd-servers=http://localhost:2379" ]
      - name: etcd
        imagePullPolicy: Never
        image: k8s.gcr.io/etcd:3.2.24
        command: [ "etcd", "--advertise-client-urls=http://0.0.0.0:2379" ]
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: apiserver
  name: cluster-apiserver
  namespace: cluster
spec:
  ports:
  - nodePort: 30000
    port: 443
    protocol: TCP
    targetPort: 443
  selector:
    app: apiserver
  type: NodePort
